# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(num)
  (1..num).inject( [0, 1] ) { | fib | fib << fib.last(2).inject(:+) }
end

def multiple(fib)
  sum = 0

  fib.each do |number|
    if number.remainder(2) == 0
      sum += number
    end
  end

  sum
end

# do not enter 4_000_000
puts multiple(fibonacci(10))
